version: '3'
services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_PASSWORD: rails
      POSTGRES_USER: rails
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/domicile