version: '3.4'
services:
  postgres:
    image: postgres:11.4
    restart: always

  web:
    image: domicile_web
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  delayed_job:
    image: domicile_web
    command: /usr/bin/job-entrypoint.sh
    entrypoint: ''
    depends_on:
      - postgres
      - web

  cron_job:
    image: domicile_web
    command: /usr/bin/cron-entrypoint.sh
    entrypoint: ''
    depends_on:
      - postgres
      - web
