version: '3.4'
services:
  postgres:
    image: postgres:11.4
    restart: always
    volumes:
      - db_tmp:/var/run

  web:
    image: domicile_web
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  delayed_job:
    image: domicile_web
    command: bundle exec rails jobs:work
    entrypoint: ''
    depends_on:
      - postgres
      - web

  cron_job:
    image: domicile_web
    command: /usr/bin/cron-entrypoint.sh
    entrypoint: ''
    depends_on:
      - postgres
      - web

volumes:
  db_tmp: &tmp_fs
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
