# version: '3'

# services:
#   postgres:
#     image: postgres:11.4
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#   web:
#     build: .
#     volumes:
#       - .:/domicile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres

version: '3'
services:
  db:
    image: postgres:11.4
    restart: always
  web:
    build: .
    restart: always
    volumes:
      - .:/domicile
    ports:
      - "3000:3000"
    depends_on:
      - db