version: '3.4'
services:
  postgres:
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - /var/lib/domicile/data/db/development:/var/lib/postgresql/data

  web:
    image: domicile_web:dev
    volumes:
      - .:/domicile
      - web_node_modules:/domicile/node_modules/
      - web_tmp:/domicile/tmp/

volumes:
  web_node_modules:
  web_tmp: &tmp_fs
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
