version: '3.4'
services:
  postgres:
    environment: &prod_shared_postgres_config
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  web:
    image: domicile_web:prod
    restart: always
    environment:
      <<: *prod_shared_postgres_config
      <<: &prod_shared_web_config
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  delayed_job:
    image: domicile_web:prod
    restart: always
    environment:
      <<: *prod_shared_web_config
      <<: *prod_shared_postgres_config

  cron_job:
    image: domicile_web:prod
    restart: always
    environment:
      <<: *prod_shared_web_config
      <<: *prod_shared_postgres_config

volumes:
  postgres_prod_data:
