version: '3.4'
services:
  postgres:
    environment:
      <<: &dev_shared_postgres_config
        POSTGRES_USER: rails
        POSTGRES_PASSWORD: rails
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  web:
    image: domicile_web:dev
    environment: *dev_shared_postgres_config
    volumes: &dev_web_volumes
      - .:/domicile
      - web_node_modules:/domicile/node_modules/
      - web_tmp:/domicile/tmp/

  delayed_job:
    image: domicile_web:dev
    environment: *dev_shared_postgres_config
    volumes: *dev_web_volumes

  cron_job:
    image: domicile_web:dev
    environment: *dev_shared_postgres_config
    volumes: *dev_web_volumes

volumes:
  web_node_modules:
  postgres_dev_data:
  web_tmp: &tmp_fs
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
