default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: rails
  password: rails
  port: 5432

development:
  <<: *default
  database: domicile_development

test:
  <<: *default
  database: domicile_test

production:
  <<: *default
  database: domicile_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
